### 0.import库

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
matrix_1 = np.zeros((3,4))

In [3]:
matrix_1

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [6]:
np.reshape(matrix_1, (6,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [4]:
matrix_2 = tf.zeros((3,4))

In [5]:
matrix_2

<tf.Tensor 'zeros:0' shape=(3, 4) dtype=float32>

In [7]:
tf.reshape(matrix_2, (2,6))

<tf.Tensor 'Reshape:0' shape=(2, 6) dtype=float32>

In [9]:
print(matrix_2)

Tensor("zeros:0", shape=(3, 4), dtype=float32)


### 1.constant运算

In [2]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
with tf.Session() as sess:
	writer = tf.summary.FileWriter('./graphs/const_add', sess.graph)
	print(sess.run(x))
writer.close()

5


In [4]:
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.multiply(a, b, name='dot_product')
with tf.Session() as sess:
	writer = tf.summary.FileWriter('./graphs/const_mul', sess.graph) 
	print(sess.run(x))
writer.close()

[[0 2]
 [4 6]]


In [11]:
a = tf.constant([[2, 2],[1, 4]], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.multiply(a, b, name='dot_product')
y = tf.matmul(a, b, name='mat_mul')
with tf.Session() as sess:
	writer = tf.summary.FileWriter('./graphs/const_mul_2', sess.graph) 
	print(sess.run(x))
	print(sess.run(y))
writer.close()

[[ 0  2]
 [ 2 12]]
[[ 4  8]
 [ 8 13]]


### 2.各式各样的常量

In [6]:
x = tf.zeros([2, 3], tf.int32)
y = tf.zeros_like(x, optimize=True)

In [7]:
print(y)

Tensor("zeros_like_1:0", shape=(2, 3), dtype=int32)


In [10]:
with tf.Session() as sess:
	y = sess.run(y)
print(y)

[[0 0 0]
 [0 0 0]]


In [14]:
t_0 = 19 
x = tf.zeros_like(t_0) # ==> 0
y = tf.ones_like(t_0) # ==> 1

with tf.Session() as sess:
	print(sess.run([x]))
	print(sess.run([y]))

[0]
[1]


### 3.变量

In [15]:
with tf.variable_scope('meh') as scope:
	a = tf.get_variable('a', [10])
	b = tf.get_variable('b', [100])

writer = tf.summary.FileWriter('./graphs/test', tf.get_default_graph())

#### 例如：求导也是一个运算

In [16]:
x = tf.Variable(2.0)
y = 2.0 * (x ** 3)
z = 3.0 + y ** 2
grad_z = tf.gradients(z, [x, y])
with tf.Session() as sess:
	sess.run(x.initializer)
	print(sess.run(grad_z))

[768.0, 32.0]


#### 可以通过下面的方式赋值

In [17]:
W = tf.Variable(10)
assign_op = W.assign(100)

with tf.Session() as sess:
	sess.run(W.initializer)
	print(W.eval())
	print(sess.run(assign_op))

10
100


#### 一次性初始化所有变量

In [18]:
my_var = tf.Variable(2, name="my_var") 

my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())
	print(sess.run(my_var_times_two))
	print(sess.run(my_var_times_two))
	print(sess.run(my_var_times_two))

4
8
16


### 4.placeholder

In [20]:
a = tf.placeholder(tf.float32, shape=[3])

# 创建常量b，但是注意这里的数据类型
b = tf.constant([5, 5, 5], tf.float32)

# use the placeholder as you would a constant
c = a + b  # tf.add(a, b)的缩略写法

with tf.Session() as sess:
	#print(sess.run(c)) # InvalidArgumentError 因为a现在没有值！
    
	# 通过字典{a: [1, 2, 3]}的形式送到placeholder里
	# 然后就可以计算c的值了
	print(sess.run(c, {a: [1, 2, 3]})) # >> [6. 7. 8.]

[ 6.  7.  8.]


In [21]:
a = tf.add(2, 5)
b = tf.multiply(a, 3)

with tf.Session() as sess:
	# 我们送进去的a是15
	replace_dict = {a: 15}

	print(sess.run(b, feed_dict=replace_dict))

45
