## Introduction to TensorFlow
by Johnson

### 0.import

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
m = np.zeros((3,4))

In [4]:
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.reshape(m, (6,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
mt = tf.zeros((3,4))

In [8]:
mt

<tf.Tensor 'zeros:0' shape=(3, 4) dtype=float32>

In [10]:
tf.reshape(mt, (2,6))

<tf.Tensor 'Reshape:0' shape=(2, 6) dtype=float32>

In [11]:
print(mt)

Tensor("zeros_1:0", shape=(3, 4), dtype=float32)


### 1. Constant operations

In [12]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
with tf.Session() as sess:
	writer = tf.summary.FileWriter('./graphs', sess.graph)
	print(sess.run(x))
writer.close()

5


In [13]:
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.multiply(a, b, name='dot_product')
with tf.Session() as sess:
	writer = tf.summary.FileWriter('./graphs', sess.graph) 
	print(sess.run(x))
writer.close()

[[0 2]
 [4 6]]


In [14]:
a = tf.constant([[2, 2],[1, 4]], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.multiply(a, b, name='dot_product')
y = tf.matmul(a, b, name='mat_mul')
with tf.Session() as sess:
	writer = tf.summary.FileWriter('./graphs', sess.graph) 
	print(sess.run(x))
	print(sess.run(y))
writer.close()

[[ 0  2]
 [ 2 12]]
[[ 4  8]
 [ 8 13]]


### 2. Constants

In [15]:
x = tf.zeros([2, 3], tf.int32)
y = tf.zeros_like(x, optimize=True)

In [16]:
print(y)

Tensor("zeros_like:0", shape=(2, 3), dtype=int32)


In [17]:
with tf.Session() as sess:
	y = sess.run(y)
print(y)

[[0 0 0]
 [0 0 0]]


In [19]:
t_0 = 19 
x = tf.zeros_like(t_0) # ==> 0
y = tf.ones_like(t_0) # ==> 1

with tf.Session() as sess:
	print(sess.run([x]))
	print(sess.run([y]))

[0]
[1]


### 3. Variables

In [20]:
with tf.variable_scope('meh') as scope:
	a = tf.get_variable('a', [10])
	b = tf.get_variable('b', [100])

writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())

#### Gradient computation is also an operator

In [21]:
x = tf.Variable(2.0)
y = 2.0 * (x ** 3)
z = 3.0 + y ** 2
grad_z = tf.gradients(z, [x, y])
with tf.Session() as sess:
	sess.run(x.initializer)
	print(sess.run(grad_z))

[768.0, 32.0]


#### Variable assignment

In [22]:
W = tf.Variable(10)
assign_op = W.assign(100)

with tf.Session() as sess:
	sess.run(W.initializer)
	print(W.eval())
	print(sess.run(assign_op))

10
100


#### Initialize all the variables

In [23]:
my_var = tf.Variable(2, name="my_var") 

my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())
	print(sess.run(my_var_times_two))
	print(sess.run(my_var_times_two))
	print(sess.run(my_var_times_two))

4
8
16


### 4. Placeholder

In [24]:
a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5, 5, 5], tf.float32)

# use the placeholder as you would a constant
c = a + b 

with tf.Session() as sess:
	print(sess.run(c)) # Error, because a has not been filled with values

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [3]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder', defined at:
  File "c:\Users\admin\anaconda3\envs\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Users\admin\anaconda3\envs\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\ipykernel\kernelapp.py", line 619, in start
    self.io_loop.start()
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\admin\anaconda3\envs\python36\lib\asyncio\base_events.py", line 442, in run_forever
    self._run_once()
  File "c:\Users\admin\anaconda3\envs\python36\lib\asyncio\base_events.py", line 1462, in _run_once
    handle._run()
  File "c:\Users\admin\anaconda3\envs\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tornado\ioloop.py", line 688, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tornado\gen.py", line 814, in inner
    self.ctx_run(self.run)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tornado\gen.py", line 162, in _fake_ctx_run
    return f(*args, **kw)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tornado\gen.py", line 775, in run
    yielded = self.gen.send(value)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\ipykernel\kernelbase.py", line 358, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tornado\gen.py", line 162, in _fake_ctx_run
    return f(*args, **kw)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\ipykernel\kernelbase.py", line 261, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tornado\gen.py", line 162, in _fake_ctx_run
    return f(*args, **kw)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\ipykernel\kernelbase.py", line 538, in execute_request
    user_expressions, allow_stdin,
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tornado\gen.py", line 162, in _fake_ctx_run
    return f(*args, **kw)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\ipykernel\ipkernel.py", line 302, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\ipykernel\zmqshell.py", line 539, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\IPython\core\interactiveshell.py", line 2867, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\IPython\core\interactiveshell.py", line 2895, in _run_cell
    return runner(coro)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\IPython\core\interactiveshell.py", line 3072, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\IPython\core\interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-4301f3688626>", line 1, in <module>
    a = tf.placeholder(tf.float32, shape=[3])
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1808, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5835, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "c:\Users\admin\anaconda3\envs\python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float and shape [3]
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [25]:
a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5, 5, 5], tf.float32)

# use the placeholder as you would a constant
c = a + b 

with tf.Session() as sess:
	print(sess.run(c, {a: [1, 2, 3]})) # Correct now, value = [6, 7, 8]

[6. 7. 8.]


In [26]:
a = tf.add(2, 5)
b = tf.multiply(a, 3)

with tf.Session() as sess:
    # Replace the value of a as 15
	replace_dict = {a: 15}
	print(sess.run(b, feed_dict=replace_dict))

45
